# Generated by Django 4.1 on 2024-06-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
