# Generated by Django 4.1 on 2024-06-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0003_remove_customfield_tenant_remove_customfield_user_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_custom_fields', to='custom_fields.customfield'),
        ),
    ]
