# Generated by Django 4.1 on 2024-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('INR', 'Indian Rupee')], default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
