# Generated by Django 4.1 on 2024-06-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0005_alter_customfield_entity_id_and_more'),
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='custom_fields',
            field=models.ManyToManyField(blank=True, related_name='interaction_custom_fields', to='custom_fields.customfield'),
        ),
    ]
