# Generated by Django 4.1 on 2024-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0002_rename_name_customfield_custom_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='user',
        ),
        migrations.AddField(
            model_name='customfield',
            name='tenant_id',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customfield',
            name='user_id',
            field=models.IntegerField(default=7),
        ),
    ]
