# Generated by Django 4.1 on 2024-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0003_remove_customfield_tenant_remove_customfield_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='entity_id',
            field=models.IntegerField(default=1),
        ),
    ]
